In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('dataset_for_analyst_assignment.csv')

df.head(3)

,REGISTRATION_DATE,REGISTRATION_COUNTRY,PURCHASE_COUNT,PURCHASE_COUNT_DELIVERY,PURCHASE_COUNT_TAKEAWAY,FIRST_PURCHASE_DAY,LAST_PURCHASE_DAY,USER_ID,BREAKFAST_PURCHASES,LUNCH_PURCHASES,...,WEB_PURCHASES,ANDROID_PURCHASES,PREFERRED_RESTAURANT_TYPES,USER_HAS_VALID_PAYMENT_METHOD,MOST_COMMON_HOUR_OF_THE_DAY_TO_PURCHASE,MOST_COMMON_WEEKDAY_TO_PURCHASE,AVG_DAYS_BETWEEN_PURCHASES,MEDIAN_DAYS_BETWEEN_PURCHASES,AVERAGE_DELIVERY_DISTANCE_KMS,PURCHASE_COUNT_BY_STORE_TYPE
0,2019-09-01 00:00:00.000,DNK,0,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,"{\n ""General merchandise"": 0,\n ""Grocery"": 0..."
1,2019-09-01 00:00:00.000,FIN,1,1.0,0.0,2020-09-02 00:00:00.000,2020-09-02 00:00:00.000,2,0.0,1.0,...,0.0,1.0,NaN,False,23.0,2.0,NaN,NaN,6.853,"{\n ""General merchandise"": 0,\n ""Grocery"": 0..."
2,2019-09-01 00:00:00.000,DNK,19,19.0,0.0,2019-12-10 00:00:00.000,2020-05-25 00:00:00.000,3,0.0,4.0,...,19.0,0.0,NaN,True,21.0,2.0,9.0,3.0,6.559,"{\n ""General merchandise"": 1,\n ""Grocery"": 9..."

In [5]:
for col in df.columns:
    dtype = df[col].dtype
    value_in_first_row = df.iloc[0][col]
    print(f"{col} - {dtype}, {value_in_first_row}")

REGISTRATION_DATE - object, 2019-09-01 00:00:00.000
REGISTRATION_COUNTRY - object, DNK
PURCHASE_COUNT - int64, 0
PURCHASE_COUNT_DELIVERY - float64, nan
PURCHASE_COUNT_TAKEAWAY - float64, nan
FIRST_PURCHASE_DAY - object, nan
LAST_PURCHASE_DAY - object, nan
USER_ID - int64, 1
BREAKFAST_PURCHASES - float64, nan
LUNCH_PURCHASES - float64, nan
EVENING_PURCHASES - float64, nan
DINNER_PURCHASES - float64, nan
LATE_NIGHT_PURCHASES - float64, nan
TOTAL_PURCHASES_EUR - float64, nan
DISTINCT_PURCHASE_VENUE_COUNT - float64, nan
MIN_PURCHASE_VALUE_EUR - float64, nan
MAX_PURCHASE_VALUE_EUR - float64, nan
AVG_PURCHASE_VALUE_EUR - float64, nan
PREFERRED_DEVICE - object, ios
IOS_PURCHASES - float64, nan
WEB_PURCHASES - float64, nan
ANDROID_PURCHASES - float64, nan
PREFERRED_RESTAURANT_TYPES - object, nan
USER_HAS_VALID_PAYMENT_METHOD - bool, False
MOST_COMMON_HOUR_OF_THE_DAY_TO_PURCHASE - float64, nan
MOST_COMMON_WEEKDAY_TO_PURCHASE - float64, nan
AVG_DAYS_BETWEEN_PURCHASES - float64, nan
MEDIAN_DAYS_BETWEEN_PURCHASES - float64, nan
AVERAGE_DELIVERY_DISTANCE_KMS - float64, nan
PURCHASE_COUNT_BY_STORE_TYPE - object, {
  "General merchandise": 0,
  "Grocery": 0,
  "Pet supplies": 0,
  "Restaurant": 0,
  "Retail store": 0
}